[package]
name = "workflow-parser"
version = "0.1.0"
authors = ["Hayden Faulds <fauldsh@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
